### ISSUE TITLE
Please rename 'Default' profile to something else to avoid overwriting user's profiles

### ISSUE THREAD

**Issue by eugenesvk** [gabriel-gardner/modtap-karabiner#1]
Thanks a bunch for the modtap example, conceptually it seems like the best solution to the home row mods issue, will see if it works!
However, to make the example a bit easier to test it might be better to rename it (e.g., to `goku` or something) to allow users to import it to another profile, test it etc. without losing their main profile, and then just copy&paste it to their main profile if they like it
And if you don't have this 'goku' profile, goku will warn you on import, so it's easy to fix vs. having to restore your default

**Comment by gabriel-gardner** [comment]
Good call! I have renamed the profile in each example to `goku`.

Did this solution work for you? I see you tagged me in another thread with a config that looked like it would even work with dual modifiers. I haven't tried this type of setup with complex modifiers but I think in theory it would work.

**Comment by eugenesvk** [comment]
Yeah, this is exactly what I'm still testing, getting a few issues that I hope are solvable with timing tweaks on individual mods (seems that some fingers spend a bit longer on their "base" key than others in some combos), also some goku changes could help reduce the boilerplate.
But in general very hopeful that this could be the solution, so thanks again for the idea (also agree with your assessment that the simultaneous method is more typo prone)

Ideally you'd also need to somehow track mode in modal text editors to disable the right side's home row mods outside of insert mode not to lose cursor key repeats on hold, maybe via another variable that's tied to the keys that switch modes...

(I've also added space mod using the same method, see if can tweak timings too make this waste of space into something useful)

**Comment by gabriel-gardner** [comment]
Apologies on late reply -- did you get it working?

As far as tracking mode in modal text editors, I haven't tried it with this setup but have you seen application identifiers within Karabiner Elements? See the "Tap a to insert 1" example in Chrome [here](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/tutorial.md). There is probably some way to get application identifiers working with my setup but could become a nightmare managing all the layers and variables. Not sure if it can check if you are in a certain state within that application though.

I use Vim as my text editor and for the most part I just learned ways to avoid holding down keys that I had mapped with this setup. It was actually helpful for me to learn to stop holding "w" in normal, etc, and get better with jump plugins like Leap.nvim. I do have a special key to disable and enable this setup for cases where I do need to hold keys like within the Unity editor.

Lastly I'll say my setup has been greatly aided by having a mechanical keyboard with which I can also use QMK to do some of the keyboard mappings. QMK can't map to higher levels of abstraction like Apple Script or Keyboard Maestro but I find it more efficient for like remapping keys to modifiers and getting the most out of the space key. Here is my [keyboard setup](https://configure.zsa.io/ergodox-ez/layouts/DnZP7/latest/0) on the Ergodox for your curiosity.

Let me know if I can help otherwise I hope the process is going well and you've found a setup that works for you!

**Comment by eugenesvk** [comment]
It's mostly working well (though there is a Goku bug with <kbd>;</kbd> in multiple modifier combos)

Re. the modal editors: I know about app ids and use them, that's the first part of the equation, though also non-working: these conditions can't track terminal editors since the frontmost app is the terminal, not the editor (otherwise I _think_ it wouldn't be too much of a nightmare to add one last branching condition (inside an editor/outside an editor)).
But then there is the second part re. the app mode that is also not solved reliably

Since both parts are flaky I haven't attempted to try find a fix and in the meantime I've resolved to
- using space-mode to disable home row mods and have the same keys as a repeatable cursor, but otherwise
- taking this limitation as an opportunity to use more word-based/half pageup/down movement keys (+ search inline to jump to a given word faster) to not rely on holding the cursor keys (so similar to your "learned ways to avoid holding down keys")

(another bright idea I had would be for the editor to set env var on every mode switch, but then karabiner doesn't have env var as conditions, so that's also not leading anywhere...)

> QMK to do some of the keyboard mappings

Yeah, that's great and should be more robust, wish the laptops supported this...

**Comment by gabriel-gardner** [comment]
> Re. the modal editors

Good point that Terminal is the frontmost app and not the editor you are using within. One idea would be to use a terminal emulator (iTerm2, Alacritty) solely for code editing and check for that instead of terminal, but definitely not an optimal solution. And you're right I don't think there is a way to add conditionals for the mode an app is in without a lot of very custom apple scripting.

> in the meantime I've resolved to

Sounds like the part of your setup that I show in this repo is working atleast. I agree that having QMK handle alterations like homerow mods, and using this goku setup for calls to higher levels (apple script, Keyboard Maestro) is the cleanest way to do it for now. Best of luck optimizing your keyboard and feel free to re-open this issue if something goes wrong 🙂
